### ISSUE TITLE
Cannot connect to Dooya DT360E

### ISSUE THREAD

**Issue by oscarliuyc** [eschava/broadlink-mqtt#100]
Hi,

I'm excited to find this project as I have 4 DT360E and I want to connected them directly to Homeassistant.

I followed the instructions, and have the following setup:

> 
> `# Type of device. Valid options are 'lookup', 'multiple_lookup', 'rm', 'rm4', '$`
> `#device_type = 'lookup' # use lookup`
> `device_type = "dooya"`
> 
> `## lookup parameters`
> `lookup_timeout = 240`
> `local_address = '192.168.11.170'`
> 
> `## parameters for direct connection`
> `device_host = '192.168.11.126'`
> `device_mac  = 'c8:93:46:31:59:a5'`

I get the following errors:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/broadlink/device.py", line 293, in send_packet
    resp = conn.recvfrom(2048)[0]
socket.timeout: timed out

During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
>   File "mqtt.py", line 596, in <module>
>     devices = get_device(cf)
>   File "mqtt.py", line 400, in get_device
>     return configure_device(device, topic_prefix)
>   File "mqtt.py", line 404, in configure_device
>     device.auth()
>   File "/usr/local/lib/python3.6/dist-packages/broadlink/device.py", line 186, in auth
>     response = self.send_packet(0x65, payload)
>   File "/usr/local/lib/python3.6/dist-packages/broadlink/device.py", line 297, in send_packet
>     raise exception(-4000)  # Network timeout.
> broadlink.exceptions.NetworkTimeoutError: [Errno -4000] Network timeout
> oscar@ubunt1804:~/broadlink-mqtt$
> 

Can you shred me some lights about what went wrong?  What's the correct configuration?

**Comment by eschava** [comment]
Did you try device_type='multiple_lookup' with correct local_address parameter?

**Comment by oscarliuyc** [comment]
I tried but none of the DT360E devices appear
