### ISSUE TITLE
Issue running two instances of mqtt.py

### ISSUE THREAD

**Issue by schwan1** [eschava/broadlink-mqtt#23]
I can not seem to figure out what is causing this issue. I have created a copy of the broadlink-mqtt-master directory with a new name. I modified the conf file to be directed to the IP address and modified the mqtt topic. I still am getting the following error when I try to run the second instance.
Please let me know where  I am going wrong.

Traceback (most recent call last):
  File "mqtt.py", line 262, in <module>
    device = get_device(cf)
  File "mqtt.py", line 202, in get_device
    logging.error('More than one Broadlink device found (' + ', '.join([d.host for d in devices]) + ')')
TypeError: sequence item 0: expected string, tuple found**

**Comment by schwan1** [comment]
I discovered my error. I did not modify the device.type in the mqtt.conf file.
