### ISSUE TITLE
socket.error: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by multima** [eschava/broadlink-mqtt#27]
Hi,
I get the below error when I lunch mqtt.py. 

[2018-05-20 10:54:14,535] DEBUG Connected to RM2 Broadlink device at '192.168.0.56' (MAC xx:xx:xx:xx:xx:xx)
Traceback (most recent call last):
  File "mqtt.py", line 385, in <module>
    mqttc.connect(cf.get('mqtt_broker', 'localhost'), int(cf.get('mqtt_port', '1883')), 60)
  File "/home/pi/.local/lib/python2.7/site-packages/paho/mqtt/client.py", line 768, in connect
    return self.reconnect()
  File "/home/pi/.local/lib/python2.7/site-packages/paho/mqtt/client.py", line 895, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 111] Connection refused

**Comment by eschava** [comment]
Do you have MQTT broker run at the local box?

**Comment by yz665** [comment]
I have same issue. Anyone resolved it ?

**Comment by eschava** [comment]
@yz665 Same question: Do you have MQTT broker run at the local box?

**Comment by g0tama** [comment]
Hi
I have the same issue. And I think I have a broker on local box. Any solution to resolve it?
Thanks

**Comment by yz665** [comment]
I solved my problem by  run "mosquito -d" command. Good luck
