### ISSUE TITLE
hi,

### ISSUE THREAD

**Issue by hamwong** [eschava/broadlink-mqtt#5]
can you add exception at code for time out? so code can keep running once there is time out

 [2017-02-26 18:00:37,667] DEBUG Sending RM temperature 19.8 to topic broadlink/temperature
[2017-02-26 18:04:37,851] DEBUG Sending RM temperature 19.6 to topic broadlink/temperature
[2017-02-26 18:08:38,792] ERROR Error
Traceback (most recent call last):
  File "/home/pi/broadlink-mqtt/mqtt.py", line 197, in run
    self.scheduler.run()
  File "/usr/lib/python2.7/sched.py", line 117, in run
    action(*argument)
  File "/home/pi/broadlink-mqtt/mqtt.py", line 184, in broadlink_rm_temperature_timer
    temperature = str(device.check_temperature())
  File "/usr/local/lib/python2.7/dist-packages/broadlink-0.3-py2.7.egg/broadlink/__init__.py", line 569, in check_temperature
    response = self.send_packet(0x6a, packet)
  File "/usr/local/lib/python2.7/dist-packages/broadlink-0.3-py2.7.egg/broadlink/__init__.py", line 342, in send_packet
    response = self.cs.recvfrom(1024)
timeout: timed out

Code than stopped here, but actually  it still running on background
[20:00:45] pi@openHABianPi:~$ ps aux | grep mqtt
pi        8470  0.0  0.1   5888  1948 pts/2    S+   20:00   0:00 grep --color=auto mqtt
pi       24833  0.0  1.0  25152 10524 pts/2    S    09:20   0:10 python /home/pi/broadlink-mqtt/mqtt.py

**Comment by eschava** [comment]
Done
Thanks for feedback!

**Comment by hamwong** [comment]
Thanks, I just update the code, and will do it on a long run see will any issue come up, 
Thanks for your hard works.

**Comment by hamwong** [comment]
still the same

**Comment by eschava** [comment]
Hi,

for some reason I have different line numbers
Is there any local changes in your version?

**Comment by hamwong** [comment]
I only add one more line in line 165 and modify few line after, but that only for work with another branch of broadlink library
	name = (cf.get('device_name'))
        if device_type == 'rm':
            return broadlink.rm(host=host, mac=mac, name=name)
        elif device_type == 'sp1':
            return broadlink.sp1(host=host, mac=mac, name=name)
        elif device_type == 'sp2':
            return broadlink.sp2(host=host, mac=mac, name=name)
        elif device_type == 'a1':
            return broadlink.a1(host=host, mac=mac, name=name)
        elif device_type == 'mp1':
            return broadlink.mp1(host=host, mac=mac, name=name)

**Comment by eschava** [comment]
Found and fixed
Thank you!

**Comment by hamwong** [comment]
Thank you for all you did,
I will do a long run test agian

**Comment by hamwong** [comment]
I think no issue so far, Thank you, it's excellent
